config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'

  devise_for :users

  resources :lists do
    resources :list_items do 
      member do
        patch :complete
      end
    end
  end

  get 'pages/about'

end

  

app/models/list.rb
class List < ActiveRecord::Base
	belongs_to :user
	has_many :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
  #line 4 adds new item to top of list and keeps in position correctly for delete or complete
  default_scope { order('created_at DESC') }

  def completed?
  	!completed_at.blank?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
  	 #devise provides its own, locate to style or replace with this one
  	 #flash[:success] = "You are now signed in."
     lists_path
  end

  def after_sign_out_path_for(user)
  	 #devise provides its own, locate to style or replace with this one
  	 #flash[:success] = "You are now signed out."
  	 root_path
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController

	before_action :set_list
	before_action :set_list_item, except: [:create, :priority]

	def create
		#must be @list.list_items with an s, due to routes created
		@list_item = @list.list_items.create(list_item_params)
		redirect_to @list
	end

	def complete
		@list_item.update_attribute(:completed_at, Time.now)
		redirect_to @list
	end

	def destroy
		#must be @list_item singular due to routes created
		if @list_item.destroy
			flash[:success] = "Item deleted!"
		else
			flash[:error] = "This item could not be deleted."
		end
		redirect_to @list
	end
	
	private
		#this method matches example, but if you use the same method
		#from the List controller to set the list it doesn't work!!!
		def set_list
			@list = List.find(params[:list_id])
		end

		def set_list_item
			@list_item = @list.list_items.find(params[:id])
		end

		def list_item_params
			params[:list_item].permit(:content, :priority)
		end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  #this line prevents access to any of the list urls or actions
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  
  respond_to :html

  def index
    @lists = current_user.lists
    respond_with(@lists)
  end

  def show
    #TODO : instead of allowing another signed-in user to type
    #URL and view another user's lists, it throws an error b/c list doesn't exist
    #how to use the error to show msg and redirect?
    #remember set_list is called first from above
    #@list.user_id may be useful here
    respond_with(@list)
    
  end

  def new
    @list = List.new
    respond_with(@list)
  end

  def edit
    #remember set_list is called first from above
  end

  def create
    @list = List.new(list_params)
    @list.save
    #respond_with(@list)
    redirect_to action: :index
  end

  def update
    @list.update(list_params)
    respond_with(@list)
  end

  def destroy
    @list.destroy
    respond_with(@list)
  end

  private

    def set_list
      #@list = current_user.lists.find(params[:id])
      @list = current_user.lists.find_by_id(params[:id])
    end

    def list_params
      params.require(:list).permit(:title, :description, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	  <title>Lists</title>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
</head>
	<body>

		<nav class="navbar navbar-default">
			<div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				        <span class="sr-only">Toggle navigation</span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			      	</button>
			      <%=link_to 'List-It', root_path, class: 'navbar-brand' %>
		    	</div>

	    		<!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        
			        <li><%=link_to 'About', pages_about_path, class: 'navbar-link' %></li>
			        
			      </ul>
  
				      <ul class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
							<li><a class="navbar-link">Logged in as <strong><%= current_user.email %></strong></a></li>
					  	  	<li class="dropdown">
				          	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Your Account <span class="caret"></span></a>
				          <ul class="dropdown-menu" role="menu">
				         
				            <li><%= link_to 'Your Lists', lists_path, :class => 'navbar-link' %></li>
				            <li><%= link_to 'Create a New List', new_list_path, :class => 'navbar-link' %></li>
				            <li><%= link_to 'Manage Your Account', edit_user_registration_path, :class => 'navbar-link' %></li>
				            <li class="divider"></li>
				            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
				          </ul>
				        </li>
						<% else %>
				  			<li><%= link_to "Create an Account", new_user_registration_path, class: 'navbar-link' %></li>
				  			<li><%= link_to "Log In", new_user_session_path, class: ' navbar-link'  %></li>
						<% end %>
					</ul>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

		<div id="notice-wrapper">
			<% if notice %>
				<p class="notice"><%= notice %></p>
			<% elsif alert %>
				<p class="alert"><%= alert %></p>
			<% elsif flash %>
				<% flash.each do |name, msg| %>
	 				<%= content_tag(:p, class: "alert alert-#{name}") do %>
	    			<%= msg %>
	    			<% end %>
				<% end %> 
			<% end %>
		</div>
		 
			<div class="page-wrap">

				<%= yield %>

				<hr />
			</div><!--/.page-wrap-->
		</div><!--/.container-->
	</body>
</html>

app/views/list_items/_form.html.erb
<%= form_for ([@list, @list.list_items.build]) do |f| %>

	<div class="form-group">
		<%= f.text_field :content, placeholder: "New List Item", class: 'form-control input-custom' %>
   </div>
   
	<div class="form-group">
		<%= f.check_box :priority %>
		<%= f.label :priority, "Mark as Priority" %>
	</div>
	
	<div class="form-group">
		<%= f.submit 'Add List Item' , class: 'btn btn-custom'%>
	</div>

<% end %>

app/views/list_items/_list_item.html.erb
<tr>
	<% if list_item.completed? %>
		<td><span class='glyphicon glyphicon-ok'</span></td>
		
		<td class="item-cell text-left" style="color:#666"><strike><%= list_item.content %></strike></td>

		<td class="icon-cell"><%= link_to '', list_list_item_path(@list, list_item.id), class: 'glyphicon glyphicon-trash', method: :delete %></td>
			
	<% elsif list_item.priority? %>

		<td class="icon-cell highlight"><%= link_to '', complete_list_list_item_path(@list, list_item.id), class: 'glyphicon glyphicon-remove', method: :patch %></td>

		<td class="item-cell text-left highlight"><%= list_item.content %></td>

		<td class="icon-cell highlight"><%= link_to '', list_list_item_path(@list, list_item.id), class: 'glyphicon glyphicon-trash', method: :delete %></td>

	<% else %>
			
		<td class="icon-cell"><%= link_to '', complete_list_list_item_path(@list, list_item.id), class: 'glyphicon glyphicon-remove', method: :patch %></td>

		<td class="item-cell text-left"><%= list_item.content %></td>

		<td class="icon-cell"><%= link_to '', list_list_item_path(@list, list_item.id), class: 'glyphicon glyphicon-trash', method: :delete %></td>
	<% end %>
</tr>

app/views/lists/_form.html.erb
<%= bootstrap_form_for(@list, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :description %>
  </div>
  
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.form_group do %>
      <%= f.submit %>
    <% end %>
    
  </div>

<% end %>

app/views/lists/edit.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3>Edit: <%= @list.title %></h3>
		<div class="custom-hr"></div>
	</div>
</div>

<%= render 'form' %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<span class="default-link">
			<%= link_to 'View This List', @list %>  &#8226; 
			<%= link_to 'Back to Your Lists', lists_path %>
		</span>
	</div>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12">
    <h3 class="pull-left">Your Lists</h3>
    <%= link_to 'Create A New List', new_list_path, class: 'btn btn-navy relative pull-right hvr-rectangle-out' %>
  </div>
</div>

<div class="custom-hr"></div>

<div class="row">

<% if @lists.count == 0 %>
  <div class="col-xs-12 col-md-6">
    <p>It looks like you don't have any lists yet. </p>
    <p>Click 'Create a New List' to get started.</p>
  </div>
<% else %>
<% @lists.each do |list| %>
  <div class="col-xs-12 col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title card"><%= link_to list.title, list%></h3>
            <span class="count pull-right"><%= list.list_items.count %></span> 
            <div class="clearfix"></div>
        </div>
        <div class="panel-body">
          <p><%= list.description %></p>

          <% if user_signed_in? %>
          <% if current_user.id == list.user_id %>
          <div class="text-right">
          <%= link_to '', edit_list_path(list), class: 'glyphicon glyphicon-pencil large' %>
          <%= link_to '', list, class: 'glyphicon glyphicon-trash large', title: 'Are you sure you want to delete this list?', method: :delete, data: { confirm: 'This action cannot be undone.', commit: 'Delete List' } %>
          <% end %>
        <% end %>
        </div>

        </div> 
      </div>
   </div>
 <% end %>
<% end %>

</div>

<br>

<%= link_to 'Create A New List', new_list_path, class: 'btn btn-navy up hvr-rectangle-out' %>

app/views/lists/new.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<h3>Create a New List</h3>
		<div class="custom-hr"></div>
	</div>
</div>



	<%= render 'form' %>

<div class="row">
	<div class="col-sm-8 col-sm-offset-2">
		<%= link_to 'Back to Your Lists', lists_path %>
	</div>
</div>
	
	

app/views/lists/show.html.erb
<div class="row">
	<div class="col-sm-8 col-sm-offset-2">

		<span class="default-link upper">
			<%= link_to 'Edit This List', edit_list_path(@list) %>  &#8226;  
			<%= link_to 'Back to Your Lists', lists_path %> 
		</span>
		
			<div class="text-center table-title">
				<%= @list.title %>
			</div>
			<!-- <tr>
				<td colspan="3" class="text-left"><strong>Description: </strong><%= @list.description %></td>
			</tr> -->
			<table class="table">
				<tr>
					<%= render @list.list_items %>
				</tr>
			</table>

			<%= render 'list_items/form' %>

			<span class="default-link">
				<%= link_to 'Edit This List', edit_list_path(@list) %>  &#8226;  
				<%= link_to 'Back to Your Lists', lists_path %> 
			</span>
	</div>
</div>

app/views/pages/about.html.erb
<div class="well well-lg">

	<h3>The About Page</h3>

	<div class="custom-hr"></div>
	
	<p class="about">List-It is a simple app that lets you create as many lists as you like, then add items to those lists. You can then cross-off items as you do them, or delete them entirely. Looking at all those crossed-out items should be motivating, right?</p>

	<p class="about">You will need to create an account first, but don't worry: List-It does not send out any emails other than to retreive a forgotten password.</p>

	<p class="about">I built this app to finally start putting together all the separate and varied pieces I had gathered and encountered while trying to learn Rails. Even though it is a simple app, I learned A LOT, and A LOT goes into making even a simple app. Database modeling, restricting access through controllers and views, testing, UX and design, and building out the front-end all require attention to an awful lot of details.</p>

	<p class="about">The demo form on the homepage is a JavaScript/jQuery simulation of an actual database-backed list that you would create after opening your account. This was one of my favorite parts of the project; it's nice to be able to test drive something right on the homepage BEFORE you create an account.</p>

	<p class="about">So, make a list and start getting some stuff done!</p>

	<p class="about">Sharon Hunter</p>

</div>

app/views/pages/index.html.erb
<div class="row well well-lg">
	<div class="col-sm-3 hidden-xs" id="headline">
		<h1><strong>List-It</strong></h1>
	</div>
	<div class="col-sm-9">
	   <p class="text-left">A free-to-use Rails 4 app that you can use to create and keep track of as many lists and list items as you like.</p>
	    <p>Packing lists, to-do lists, shopping lists, and so on.</p>
	    <p>Just a place to keep track of all the things you need to remember.</p>
	</div>
</div>

<!-- 		<%= link_to "Create an Account", new_user_registration_path, class: 'btn btn-default btn-lg btn-block' %>

		<p class="small text-center">Already have an account?</p>

		<%= link_to "Log In", new_user_session_path, class: 'btn btn-default btn-lg btn-block'  %> -->
		
	  <div class="col-sm-8 col-sm-offset-2">
	  	<div class="text-center table-title">
				<h3>Try This Demo!</h3>
				<p class="demo-text">Delete or check off items, <br />or add your own using the form below.</p>
			</div>

			<table class="table" id="demo-list">
					<tr>
						<td class="icon-cell-remove">
							<span class='glyphicon glyphicon-ok'></span>
						</td>
						<td class="item-cell text-left" style="color:#666">
							<strike>Wash the car.</strike>
						</td>
						<td class="icon-cell-trash">
							<a class='glyphicon glyphicon-trash' data-toggle="tooltip" data-placement="left" title="click to delete this row">
							</a>
						</td>
					</tr>
					
					<tr class='highlight'>
						<td class="icon-cell-remove">
							<a class='glyphicon glyphicon-remove' data-toggle="tooltip" data-placement="right" title="click to cross off this item">
							</a>
						</td>
						<td class="item-cell text-left">
							Vet appt. 2:30 Saturday.
						</td>
						<td class="icon-cell-trash">
							<a class='glyphicon glyphicon-trash' data-toggle="tooltip" data-placement="left" title="click to delete this row">
							</a>
						</td>
					</tr>
					
					<tr>
						<td class="icon-cell-remove">
							<a class='glyphicon glyphicon-remove' data-toggle="tooltip" data-placement="right" title="click to cross off this item">
							</a>
						</td>
						<td class="item-cell text-left">
							Buy new running shoes.
						</td>
						<td class="icon-cell-trash">
							<a class='glyphicon glyphicon-trash' data-toggle="tooltip" data-placement="left" title="click to delete this row">
							</a>
						</td>
					</tr>
				</table>
				
				 
				<form id="demo-form" onsubmit="return false">
					<div class="form-group">
						<label for="demo-list-item"></label>
						<input type="text" class="form-control input-custom" id="demo-list-item" placeholder="Add Your List Item Here">
					</div>
					
					<div class="form-group">
						<div class="checkbox">
    						<label>
      							<input type="checkbox" id="demo-checkbox"> Mark as Priority
    						</label>
    					</div>
    				</div>
	
					<div class="form-group">
						<button type="button" class="btn btn-custom" id="demo-submit-btn">Add List Item</button>
					</div>

				</form>

	  		<!-- </div> -->
	 </div>
</div> <!-- end of row -->


	
	


 